rethinkdb:
  image: rethinkdb
  ports:
    - "28015:28015"
    - "8080:8080"

horizon:
  build: .
  command: horizon --dev -c rethinkdb:28015 --bind all
  links:
    - rethinkdb
  ports:
    - "8181:8181"
